version: "3"

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - nixbuilder

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - nixbuilder

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - nixbuilder

    
  crdb:
    image: cockroachdb/cockroach:latest
    ports:
     - "26257:26257"
     - "8085:8085"
    command: start-single-node --insecure
    volumes:
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    networks:
      - nixbuilder


networks:
  nixbuilder:
    driver: bridge